name: Python Check Style
on:
  push:
    branches:
      - master

jobs:
  python-check-style:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set versions python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'

      - name: Install dependecies python
        run: |
          python -m pip install --upgrade pip

      - name: Python check style
        run: |
          pip install pycodestyle
          pycodestyle

      
